### ISSUE TITLE
Error when trying to clean material slots

### ISSUE THREAD

**Issue by 8onk** [ChrisHinde/MaterialUtilities#15]
When there's no active object and you trying to clean material slots on selected objdects, addon returns error

1. Select objects in collection

2. Click twice on checkbox of collection 
<img width="911" alt="image" src="https://github.com/ChrisHinde/MaterialUtilities/assets/105382408/35fae3c3-b137-4ea9-a557-37462054ec6a">

3. Now we have objects in collection selected, but there's no active object
<img width="910" alt="image" src="https://github.com/ChrisHinde/MaterialUtilities/assets/105382408/7b2c30b2-1a59-420c-baec-938f82a7be94">

4. Call Shift+Q menu

5. Press clean material slots

6. Error
<img width="1436" alt="image" src="https://github.com/ChrisHinde/MaterialUtilities/assets/105382408/5b2312e4-d90d-476f-aff3-e875d039d470">

 - Blender version 4.1.1
 - Add-on Version 2.2.2
 
Returns error even if you uncheck "only active object" on left bottom of viewport
<img width="326" alt="image" src="https://github.com/ChrisHinde/MaterialUtilities/assets/105382408/7558c962-c8f7-4408-bfc8-8e212b5ed1e5">

**Comment by ChrisHinde** [comment]
This should now be fixed with version 3.0.1 (dev).
You can download it from here: https://github.com/ChrisHinde/MaterialUtilities/releases/tag/v3.0.1-dev (NB: Get the [MaterialUtilities-3.0.1-dev.zip](https://github.com/ChrisHinde/MaterialUtilities/releases/download/v3.0.1-dev/MaterialUtilities-3.0.1-dev.zip), not the "Source code" files)

This will probably moved to Stable soon, but I might change the operation of the Clean Material Slots function slightly before that.

**Comment by ChrisHinde** [comment]
This should now be fixed with version 3.0.1 (dev).
You can download it from here: https://github.com/ChrisHinde/MaterialUtilities/releases/tag/v3.0.1-dev (NB: Get the [MaterialUtilities-3.0.1-dev.zip](https://github.com/ChrisHinde/MaterialUtilities/releases/download/v3.0.1-dev/MaterialUtilities-3.0.1-dev.zip), not the "Source code" files)

This will probably moved to Stable soon, but I might change the operation of the Clean Material Slots function slightly before that.
