### ISSUE TITLE
Preserve latest material when merging base names

### ISSUE THREAD

**Issue by 3dWrecker** [ChrisHinde/MaterialUtilities#16]
Would it be possible to add a checkbox to the "merge base names" option which preserves the latest version of the material rather than the base name version?

**Comment by ChrisHinde** [comment]
Sorry for the late response, I thought I had fixed this, but apparently not (life happens).

I wasn't sure that "the latest version" was the right way to go (and maybe not very "definable"). Instead I've chosen to use the selected material instead of the "base name version". So if you choose "Material.003" and enable "Use Selected Material" ([see docs](https://github.com/ChrisHinde/MaterialUtilities/blob/master/docs/usage.md#merge-base-names)), "Material.003" will be the material setup used. 

This is now implemented in the latest version (v3.0.2)
