### ISSUE TITLE
Blender non-responsive when expanding 'Assign Material' menu with huge material library

### ISSUE THREAD

**Issue by ahjulstad** [ChrisHinde/MaterialUtilities#9]
**Describe the bug**
When expanding the 'Assign Material' menu when my blend file has a very large number of materials (30 000?), Blender hangs. 

**To Reproduce**
1. Open large file
2. Select many objects (using Select Hierarchy in outliner)
3. Right click for context menu and select material utilities and assign material
4. Blender hangs.

**Expected behavior**
Perhaps a feature, but it would be great if one could quickly search for desired material, or perhaps use the active one as a simple starting point?

**Versions (please complete the following information):**
 - Blender version 2.83.0 
 - MaterialUtilities version 2.2.0

**Additional context**
My blend file is a combination of several FBX imports from Navisworks Simulate.

**Comment by ChrisHinde** [comment]
Thank you for your report!

This is due to how the materials are populated in the menu (basically one by one, which gets slow at numbers like 2000+ materials [in my test]).

As it is right now,  I see no way to either speed it up or do it another way (the "Input Boxes" [in the material panel or the "Search" option in the menu] doesn't have this problem since they are linked to the material list on a lower level).

The best option I could think of right now is simply to put a limit on the number of materials shown in the menus (now 1500, by default, changeable in the preferences).
Sadly there isn't any way to, easily or satisfactory, control what part of the material list to show, so it will always be the first 1500 (or what you choose), in alphabetical order.
My recommendation is to use the 'Search' option (which now will appear both at the top and bottom, to find the material you're looking for, in these cases.

**Comment by ChrisHinde** [comment]
This was "fixed" with the limit to number of materials shown
